/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'date' : string,
  'priority' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Language {
  'nativeName' : string,
  'code' : string,
  'name' : string,
}
export interface MemberEntity {
  'id' : bigint,
  'region' : MemberRegion,
  'status' : MemberStatus,
  'country' : string,
  'name' : string,
  'languages' : Array<string>,
  'description' : string,
  'website' : string,
  'joinedDate' : string,
  'memberType' : MemberType,
  'contactEmail' : string,
}
export type MemberRegion = { 'europe' : null } |
  { 'northAmerica' : null } |
  { 'latinAmerica' : null } |
  { 'asiaPacific' : null } |
  { 'middleEast' : null } |
  { 'global' : null } |
  { 'africa' : null };
export type MemberStatus = { 'applicant' : null } |
  { 'active' : null } |
  { 'observer' : null } |
  { 'suspended' : null };
export type MemberType = { 'ngo' : null } |
  { 'nation' : null } |
  { 'city' : null } |
  { 'community' : null } |
  { 'individual' : null } |
  { 'cooperative' : null } |
  { 'corporate' : null };
export interface PlatformStats {
  'members' : bigint,
  'communities' : bigint,
  'projects' : bigint,
  'volunteers' : bigint,
  'nations' : bigint,
  'solutions' : bigint,
}
export type StatType = { 'members' : null } |
  { 'communities' : null } |
  { 'projects' : null } |
  { 'volunteers' : null } |
  { 'nations' : null } |
  { 'solutions' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, string, string], bigint>,
  'addMember' : ActorMethod<
    [
      string,
      MemberType,
      MemberRegion,
      string,
      string,
      string,
      MemberStatus,
      Array<string>,
      string,
      string,
    ],
    bigint
  >,
  'applyForMembership' : ActorMethod<
    [
      string,
      MemberType,
      MemberRegion,
      string,
      string,
      Array<string>,
      string,
      string,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMember' : ActorMethod<[bigint], [] | [MemberEntity]>,
  'getMembers' : ActorMethod<[], Array<MemberEntity>>,
  'getStats' : ActorMethod<[], PlatformStats>,
  'getSupportedLanguages' : ActorMethod<[], Array<Language>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'removeAnnouncement' : ActorMethod<[bigint], undefined>,
  'removeMember' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateMemberStatus' : ActorMethod<[bigint, MemberStatus], undefined>,
  'updateStat' : ActorMethod<[StatType, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];