/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MemberType = IDL.Variant({
  'ngo' : IDL.Null,
  'nation' : IDL.Null,
  'city' : IDL.Null,
  'community' : IDL.Null,
  'individual' : IDL.Null,
  'cooperative' : IDL.Null,
  'corporate' : IDL.Null,
});
export const MemberRegion = IDL.Variant({
  'europe' : IDL.Null,
  'northAmerica' : IDL.Null,
  'latinAmerica' : IDL.Null,
  'asiaPacific' : IDL.Null,
  'middleEast' : IDL.Null,
  'global' : IDL.Null,
  'africa' : IDL.Null,
});
export const MemberStatus = IDL.Variant({
  'applicant' : IDL.Null,
  'active' : IDL.Null,
  'observer' : IDL.Null,
  'suspended' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Text,
  'priority' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MemberEntity = IDL.Record({
  'id' : IDL.Nat,
  'region' : MemberRegion,
  'status' : MemberStatus,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'website' : IDL.Text,
  'joinedDate' : IDL.Text,
  'memberType' : MemberType,
  'contactEmail' : IDL.Text,
});
export const PlatformStats = IDL.Record({
  'members' : IDL.Nat,
  'communities' : IDL.Nat,
  'projects' : IDL.Nat,
  'volunteers' : IDL.Nat,
  'nations' : IDL.Nat,
  'solutions' : IDL.Nat,
});
export const Language = IDL.Record({
  'nativeName' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StatType = IDL.Variant({
  'members' : IDL.Null,
  'communities' : IDL.Null,
  'projects' : IDL.Null,
  'volunteers' : IDL.Null,
  'nations' : IDL.Null,
  'solutions' : IDL.Null,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMember' : IDL.Func(
      [
        IDL.Text,
        MemberType,
        MemberRegion,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MemberStatus,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'applyForMembership' : IDL.Func(
      [
        IDL.Text,
        MemberType,
        MemberRegion,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMember' : IDL.Func([IDL.Nat], [IDL.Opt(MemberEntity)], ['query']),
  'getMembers' : IDL.Func([], [IDL.Vec(MemberEntity)], ['query']),
  'getStats' : IDL.Func([], [PlatformStats], ['query']),
  'getSupportedLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeCallerAsAdmin' : IDL.Func([], [], []),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'removeAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'removeMember' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateMemberStatus' : IDL.Func([IDL.Nat, MemberStatus], [], []),
  'updateStat' : IDL.Func([StatType, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MemberType = IDL.Variant({
    'ngo' : IDL.Null,
    'nation' : IDL.Null,
    'city' : IDL.Null,
    'community' : IDL.Null,
    'individual' : IDL.Null,
    'cooperative' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const MemberRegion = IDL.Variant({
    'europe' : IDL.Null,
    'northAmerica' : IDL.Null,
    'latinAmerica' : IDL.Null,
    'asiaPacific' : IDL.Null,
    'middleEast' : IDL.Null,
    'global' : IDL.Null,
    'africa' : IDL.Null,
  });
  const MemberStatus = IDL.Variant({
    'applicant' : IDL.Null,
    'active' : IDL.Null,
    'observer' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Text,
    'priority' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MemberEntity = IDL.Record({
    'id' : IDL.Nat,
    'region' : MemberRegion,
    'status' : MemberStatus,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'website' : IDL.Text,
    'joinedDate' : IDL.Text,
    'memberType' : MemberType,
    'contactEmail' : IDL.Text,
  });
  const PlatformStats = IDL.Record({
    'members' : IDL.Nat,
    'communities' : IDL.Nat,
    'projects' : IDL.Nat,
    'volunteers' : IDL.Nat,
    'nations' : IDL.Nat,
    'solutions' : IDL.Nat,
  });
  const Language = IDL.Record({
    'nativeName' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StatType = IDL.Variant({
    'members' : IDL.Null,
    'communities' : IDL.Null,
    'projects' : IDL.Null,
    'volunteers' : IDL.Null,
    'nations' : IDL.Null,
    'solutions' : IDL.Null,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMember' : IDL.Func(
        [
          IDL.Text,
          MemberType,
          MemberRegion,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MemberStatus,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'applyForMembership' : IDL.Func(
        [
          IDL.Text,
          MemberType,
          MemberRegion,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMember' : IDL.Func([IDL.Nat], [IDL.Opt(MemberEntity)], ['query']),
    'getMembers' : IDL.Func([], [IDL.Vec(MemberEntity)], ['query']),
    'getStats' : IDL.Func([], [PlatformStats], ['query']),
    'getSupportedLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeCallerAsAdmin' : IDL.Func([], [], []),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'removeAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'removeMember' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateMemberStatus' : IDL.Func([IDL.Nat, MemberStatus], [], []),
    'updateStat' : IDL.Func([StatType, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };