/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface MemberEntity {
    id: bigint;
    region: MemberRegion;
    status: MemberStatus;
    country: string;
    name: string;
    languages: Array<string>;
    description: string;
    website: string;
    joinedDate: string;
    memberType: MemberType;
    contactEmail: string;
}
export interface Language {
    nativeName: string;
    code: string;
    name: string;
}
export interface Announcement {
    id: bigint;
    title: string;
    body: string;
    date: string;
    priority: string;
}
export interface PlatformStats {
    members: bigint;
    communities: bigint;
    projects: bigint;
    volunteers: bigint;
    nations: bigint;
    solutions: bigint;
}
export interface UserProfile {
    name: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum MemberRegion {
    europe = "europe",
    northAmerica = "northAmerica",
    latinAmerica = "latinAmerica",
    asiaPacific = "asiaPacific",
    middleEast = "middleEast",
    global = "global",
    africa = "africa"
}
export enum MemberStatus {
    applicant = "applicant",
    active = "active",
    observer = "observer",
    suspended = "suspended"
}
export enum MemberType {
    ngo = "ngo",
    nation = "nation",
    city = "city",
    community = "community",
    individual = "individual",
    cooperative = "cooperative",
    corporate = "corporate"
}
export enum StatType {
    members = "members",
    communities = "communities",
    projects = "projects",
    volunteers = "volunteers",
    nations = "nations",
    solutions = "solutions"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnouncement(title: string, body: string, date: string, priority: string): Promise<bigint>;
    addMember(name: string, memberType: MemberType, region: MemberRegion, country: string, description: string, joinedDate: string, status: MemberStatus, languages: Array<string>, website: string, contactEmail: string): Promise<bigint>;
    applyForMembership(name: string, memberType: MemberType, region: MemberRegion, country: string, description: string, languages: Array<string>, website: string, contactEmail: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMember(id: bigint): Promise<MemberEntity | null>;
    getMembers(): Promise<Array<MemberEntity>>;
    getStats(): Promise<PlatformStats>;
    getSupportedLanguages(): Promise<Array<Language>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    removeAnnouncement(id: bigint): Promise<void>;
    removeMember(id: bigint): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateMemberStatus(id: bigint, status: MemberStatus): Promise<void>;
    updateStat(statType: StatType, value: bigint): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, MemberEntity as _MemberEntity, MemberRegion as _MemberRegion, MemberStatus as _MemberStatus, MemberType as _MemberType, StatType as _StatType, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnouncement(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addMember(arg0: string, arg1: MemberType, arg2: MemberRegion, arg3: string, arg4: string, arg5: string, arg6: MemberStatus, arg7: Array<string>, arg8: string, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0, to_candid_MemberType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_MemberRegion_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_MemberStatus_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0, to_candid_MemberType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_MemberRegion_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_MemberStatus_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
            return result;
        }
    }
    async applyForMembership(arg0: string, arg1: MemberType, arg2: MemberRegion, arg3: string, arg4: string, arg5: Array<string>, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForMembership(arg0, to_candid_MemberType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_MemberRegion_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForMembership(arg0, to_candid_MemberType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_MemberRegion_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: bigint): Promise<MemberEntity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembers(): Promise<Array<MemberEntity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembers();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembers();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getSupportedLanguages(): Promise<Array<Language>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportedLanguages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportedLanguages();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAnnouncement(arg0);
            return result;
        }
    }
    async removeMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMemberStatus(arg0: bigint, arg1: MemberStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberStatus(arg0, to_candid_MemberStatus_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberStatus(arg0, to_candid_MemberStatus_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStat(arg0: StatType, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStat(to_candid_StatType_n29(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStat(to_candid_StatType_n29(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MemberEntity_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberEntity): MemberEntity {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MemberRegion_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberRegion): MemberRegion {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_MemberStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberStatus): MemberStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MemberType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberType): MemberType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberEntity]): MemberEntity | null {
    return value.length === 0 ? null : from_candid_MemberEntity_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _MemberRegion;
    status: _MemberStatus;
    country: string;
    name: string;
    languages: Array<string>;
    description: string;
    website: string;
    joinedDate: string;
    memberType: _MemberType;
    contactEmail: string;
}): {
    id: bigint;
    region: MemberRegion;
    status: MemberStatus;
    country: string;
    name: string;
    languages: Array<string>;
    description: string;
    website: string;
    joinedDate: string;
    memberType: MemberType;
    contactEmail: string;
} {
    return {
        id: value.id,
        region: from_candid_MemberRegion_n15(_uploadFile, _downloadFile, value.region),
        status: from_candid_MemberStatus_n17(_uploadFile, _downloadFile, value.status),
        country: value.country,
        name: value.name,
        languages: value.languages,
        description: value.description,
        website: value.website,
        joinedDate: value.joinedDate,
        memberType: from_candid_MemberType_n19(_uploadFile, _downloadFile, value.memberType),
        contactEmail: value.contactEmail
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n25(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    europe: null;
} | {
    northAmerica: null;
} | {
    latinAmerica: null;
} | {
    asiaPacific: null;
} | {
    middleEast: null;
} | {
    global: null;
} | {
    africa: null;
}): MemberRegion {
    return "europe" in value ? MemberRegion.europe : "northAmerica" in value ? MemberRegion.northAmerica : "latinAmerica" in value ? MemberRegion.latinAmerica : "asiaPacific" in value ? MemberRegion.asiaPacific : "middleEast" in value ? MemberRegion.middleEast : "global" in value ? MemberRegion.global : "africa" in value ? MemberRegion.africa : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicant: null;
} | {
    active: null;
} | {
    observer: null;
} | {
    suspended: null;
}): MemberStatus {
    return "applicant" in value ? MemberStatus.applicant : "active" in value ? MemberStatus.active : "observer" in value ? MemberStatus.observer : "suspended" in value ? MemberStatus.suspended : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ngo: null;
} | {
    nation: null;
} | {
    city: null;
} | {
    community: null;
} | {
    individual: null;
} | {
    cooperative: null;
} | {
    corporate: null;
}): MemberType {
    return "ngo" in value ? MemberType.ngo : "nation" in value ? MemberType.nation : "city" in value ? MemberType.city : "community" in value ? MemberType.community : "individual" in value ? MemberType.individual : "cooperative" in value ? MemberType.cooperative : "corporate" in value ? MemberType.corporate : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberEntity>): Array<MemberEntity> {
    return value.map((x)=>from_candid_MemberEntity_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n23(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_MemberRegion_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberRegion): _MemberRegion {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MemberStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): _MemberStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_MemberType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberType): _MemberType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_StatType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatType): _StatType {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberType): {
    ngo: null;
} | {
    nation: null;
} | {
    city: null;
} | {
    community: null;
} | {
    individual: null;
} | {
    cooperative: null;
} | {
    corporate: null;
} {
    return value == MemberType.ngo ? {
        ngo: null
    } : value == MemberType.nation ? {
        nation: null
    } : value == MemberType.city ? {
        city: null
    } : value == MemberType.community ? {
        community: null
    } : value == MemberType.individual ? {
        individual: null
    } : value == MemberType.cooperative ? {
        cooperative: null
    } : value == MemberType.corporate ? {
        corporate: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatType): {
    members: null;
} | {
    communities: null;
} | {
    projects: null;
} | {
    volunteers: null;
} | {
    nations: null;
} | {
    solutions: null;
} {
    return value == StatType.members ? {
        members: null
    } : value == StatType.communities ? {
        communities: null
    } : value == StatType.projects ? {
        projects: null
    } : value == StatType.volunteers ? {
        volunteers: null
    } : value == StatType.nations ? {
        nations: null
    } : value == StatType.solutions ? {
        solutions: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberRegion): {
    europe: null;
} | {
    northAmerica: null;
} | {
    latinAmerica: null;
} | {
    asiaPacific: null;
} | {
    middleEast: null;
} | {
    global: null;
} | {
    africa: null;
} {
    return value == MemberRegion.europe ? {
        europe: null
    } : value == MemberRegion.northAmerica ? {
        northAmerica: null
    } : value == MemberRegion.latinAmerica ? {
        latinAmerica: null
    } : value == MemberRegion.asiaPacific ? {
        asiaPacific: null
    } : value == MemberRegion.middleEast ? {
        middleEast: null
    } : value == MemberRegion.global ? {
        global: null
    } : value == MemberRegion.africa ? {
        africa: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): {
    applicant: null;
} | {
    active: null;
} | {
    observer: null;
} | {
    suspended: null;
} {
    return value == MemberStatus.applicant ? {
        applicant: null
    } : value == MemberStatus.active ? {
        active: null
    } : value == MemberStatus.observer ? {
        observer: null
    } : value == MemberStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
